//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookingDetails180625
    {
        [Required(ErrorMessage = "Required")]
        public int BookingID { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> RoomID { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> UserID { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date, ErrorMessage = "Invalid Booked from date")]
        public Nullable<System.DateTime> Booked_From { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Date, ErrorMessage = "Invalid Booked to date")]
        public Nullable<System.DateTime> Booked_To { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> No_of_Adults { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> No_of_Children { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> Amount { get; set; }
    
        public virtual RoomDetails180625 RoomDetails180625 { get; set; }
        public virtual Users180625 Users180625 { get; set; }
    }
}
