//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelsEntities : DbContext
    {
        public HotelsEntities()
            : base("name=HotelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingDetails180625> BookingDetails180625 { get; set; }
        public virtual DbSet<Hotels180625> Hotels180625 { get; set; }
        public virtual DbSet<RoomDetails180625> RoomDetails180625 { get; set; }
        public virtual DbSet<Users180625> Users180625 { get; set; }
    }
}
