//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoomDetails180625
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomDetails180625()
        {
            this.BookingDetails180625 = new HashSet<BookingDetails180625>();
        }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> HotelID { get; set; }
        [Required(ErrorMessage = "Required")]
        public int RoomID { get; set; }
        [Required(ErrorMessage = "Required")]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "RoomNo length should be 10")]
        public string RoomNo { get; set; }
        [Required(ErrorMessage = "Required")]
        public string RoomType { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> Per_Night_Rate { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<bool> Availability { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetails180625> BookingDetails180625 { get; set; }
        public virtual Hotels180625 Hotels180625 { get; set; }
    }
}
